title: Bring Me The Horizon ARG Wiki
description: ALL HAIL NEX GEN
repository: bmth-arg-wiki/bmth-arg-wiki.github.io

url: "https://www.secrettinfoilsociety.com"
baseurl: ""

github_api: "https://api.github.com/repos/bmth-arg-wiki"

sass:
  load_paths:
    - _sass
    - node_modules/bulma
  style: compressed

plugins:
  - jekyll-anchor-tags
