title: Bring Me The Horizon ARG Wiki
description: ALL HAIL NEX GEN
repository: bmth-arg-wiki/bmth-arg-wiki.github.io

url: "https://www.secrettinfoilsociety.com"
baseurl: ""

sass:
  load_paths:
    - _sass
    - node_modules/bulma
  style: compressed

plugins:
  - jekyll-toc
  - jekyll-anchor-tags

toc:
  insert_toc: false
