title: Bring Me The Horizon ARG Wiki
description: ALL HAIL NEX GEN
repository: bmth-arg-wiki/bmth-arg-wiki.github.io

url: "https://www.secrettinfoilsociety.com"
baseurl: ""

plugins:
  - jekyll-anchor-tags
